.PHONY: clean All

All:
	@echo "----------Building project:[ Net2USB_Server - Debug ]----------"
	@$(MAKE) -f  "Net2USB_Server.mk"
clean:
	@echo "----------Cleaning project:[ Net2USB_Server - Debug ]----------"
	@$(MAKE) -f  "Net2USB_Server.mk" clean
